import { WASP_API_URL } from '../config'
import { loadSession, saveSession, clearSession } from './auth'
import { loadApiKeys } from './api-keys'
import type { AIProvider, UserContext, UserApiKeys } from '../../shared/types'

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

/**
 * Login with email + password via Wasp's email auth endpoint.
 * On success the session cookie is persisted to disk (encrypted).
 */
export async function loginWithEmail(email: string, password: string): Promise<void> {
  // Wasp email/password login endpoint (generated by wasp for email auth method)
  const res = await fetch(`${WASP_API_URL}/auth/email/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  })

  if (!res.ok) {
    const body = await res.json().catch(() => ({}))
    throw new Error((body as { message?: string }).message ?? 'Invalid email or password')
  }

  // Wasp returns the sessionId in the response body
  const body = await res.json().catch(() => ({})) as { sessionId?: string }
  const sessionId = body.sessionId

  if (!sessionId) {
    throw new Error('Login succeeded but no session ID was returned')
  }

  // Store the sessionId (it will be sent as Bearer token in Authorization header)
  saveSession(sessionId)
}

// ---------------------------------------------------------------------------
// Authenticated requests
// ---------------------------------------------------------------------------

type ApiResponse<T> =
  | { ok: true; data: T }
  | { ok: false; status: number; message: string }

async function request<T>(
  method: string,
  path: string,
  body?: unknown
): Promise<ApiResponse<T>> {
  const sessionId = loadSession()

  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  }

  // Send sessionId as Bearer token in Authorization header (Wasp's default auth method)
  if (sessionId) {
    headers['Authorization'] = `Bearer ${sessionId}`
  }

  const res = await fetch(`${WASP_API_URL}${path}`, {
    method,
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { message?: string }
    return { ok: false, status: res.status, message: err.message ?? res.statusText }
  }

  const data = await res.json() as T
  return { ok: true, data }
}

// ---------------------------------------------------------------------------
// Copilot API calls
// ---------------------------------------------------------------------------

export interface SubscriptionStatus {
  isActive: boolean
  subscriptionStatus: string | null
  subscriptionPlan: string | null
  availableProviders: AIProvider[]
  transcriptionsUsed: number
  transcriptionLimit: number | null
  snapshotsUsed: number
  snapshotLimit: number | null
  hasCodeSnapshot: boolean
}

export async function fetchSubscriptionStatus(): Promise<ApiResponse<SubscriptionStatus>> {
  const apiKeys = loadApiKeys()
  // Build query string with API keys if they exist
  const params = new URLSearchParams()
  if (apiKeys.anthropicApiKey) params.set('anthropicApiKey', apiKeys.anthropicApiKey)
  if (apiKeys.geminiApiKey) params.set('geminiApiKey', apiKeys.geminiApiKey)
  if (apiKeys.openaiApiKey) params.set('openaiApiKey', apiKeys.openaiApiKey)
  
  const queryString = params.toString()
  const path = queryString 
    ? `/api/copilot/subscription-status?${queryString}` 
    : '/api/copilot/subscription-status'
  
  return request<SubscriptionStatus>('GET', path)
}

export async function transcribeAudio(audioBuffer: ArrayBuffer): Promise<string> {
  const base64 = Buffer.from(audioBuffer).toString('base64')
  const apiKeys = loadApiKeys()
  const result = await request<{ transcript: string }>('POST', '/api/copilot/transcribe', { 
    audio: base64,
    apiKeys,
  })
  if (!result.ok) {
    if (result.status === 401) clearSession()
    throw new Error(result.message)
  }
  return result.data.transcript
}

export async function getAnswer(
  question: string,
  provider: AIProvider,
  context: UserContext
): Promise<string> {
  const apiKeys = loadApiKeys()
  const result = await request<{ answer: string }>('POST', '/api/copilot/answer', {
    question,
    provider,
    context,
    apiKeys,
  })
  if (!result.ok) {
    if (result.status === 401) clearSession()
    throw new Error(result.message)
  }
  return result.data.answer
}

export async function analyzeCodeSnapshot(imageBase64: string, context?: string): Promise<string> {
  const apiKeys = loadApiKeys()
  const result = await request<{ explanation: string }>('POST', '/api/copilot/code-snapshot', {
    image: imageBase64,
    context,
    apiKeys,
  })
  if (!result.ok) {
    if (result.status === 401) clearSession()
    throw new Error(result.message)
  }
  return result.data.explanation
}

// ---------------------------------------------------------------------------
// API Keys management
// ---------------------------------------------------------------------------

export { loadApiKeys, saveApiKeys, clearApiKeys, clearApiKey } from './api-keys'
export type { UserApiKeys }
